services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/data:/app/data


  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - appnet
    depends_on:
      - backend

networks:
  appnet:
